### ISSUE TITLE
Quirrel & Blitzjs not working

### ISSUE THREAD

**Issue by rahmonzoda** [quirrel-dev/quirrel#1006]
## Bug Report

**Current Behavior**
The event starts to execute, but in the end, api do not receive a request

<img width="812" alt="Screenshot 2022-04-30 at 14 45 32" src="https://user-images.githubusercontent.com/6014826/166104440-aa21020f-0ac1-425e-9e2a-5c1a2292528e.png">

**Input Code**

https://github.com/rahmonzoda/quirrel-test

for demonstration, I created a new blitsjs project according to the instructions

https://docs.quirrel.dev/getting-started/next-js
`blitz install quirrel`

I also used docker version, same result

```ts
export default Queue(
  "api/greetingsQueue", // the path of this API route
  async ({ to, message }: Greetings) => {
    console.log(`Greetings, ${to}! Thy ears shall hear: "${message}"`)
  }
)

export default async function enqueueGreeting() {
  await greetingsQueue.enqueue({
    to: "Sandy Cheeks",
    message: "Howdy!",
  })
}
```

**Expected behavior/code**
console.log(`Greetings, Sandy Cheeks! Thy ears shall hear: "Howdy!"`)

**Environment**

- Quirrel version: [v1.8.1]
- Node/npm version: [v17.9.0, npm v8.7.0]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Skn0tt** [comment]
Taking a look :eyes:

**Comment by Skn0tt** [comment]
Working fine for me with your repo. Did you change Blitz' port by chance?

![Screenshot 2022-05-02 at 13 41 33](https://user-images.githubusercontent.com/14912729/166228111-99ea011d-b291-47d8-a110-262116b7ffb1.png)

**Comment by rahmonzoda** [comment]
You're right, now it works for me too.
Strange, I must be missing something important, but I don’t understand what

I need a `https` for testing, but I set
`QUIRREL_BASE_URL=https://192.168.0.13:3000`

no other changes

**Comment by Skn0tt** [comment]
yeah, that could be related to it. have you tried opening that URL in the browser? I don't think the Blitz Dev server has HTTPS support

**Comment by rahmonzoda** [comment]
I wrote my custom server.
I have been writing the project for several weeks, but `Quirrel` installed a few days ago

**Comment by rahmonzoda** [comment]
I removed custom server and use default, but still same result
<img width="943" alt="Screenshot 2022-05-02 at 16 26 37" src="https://user-images.githubusercontent.com/6014826/166241515-b1f49a73-277a-43a5-8c8a-b86adcf9ab62.png">

what are the debugging tools for this? logs?

**Comment by rahmonzoda** [comment]
In any case, thank you for the Quirrel and Blitz are excellent libraries,
I'm still poking around. What is happening.

**Comment by Skn0tt** [comment]
The Quirrel server calls `QUIRREL_BASE_URL + {queue}`. So for this, it'd call `https://192.168.0.13:3000/api/hourlyCron`. You can try verifying that you can call this endpoint from the browser / via cURL.

**Comment by rahmonzoda** [comment]
Yeah, it works if just go through browser

**Comment by Skn0tt** [comment]
that's interesting. this is the line where the `executing job` log you're seeing is emitted:

https://github.com/quirrel-dev/quirrel/blob/153299597118e8af30277a6c2fae09762a8fa638/src/api/worker/index.ts#L86

it should print "execution done" after the request is done:

https://github.com/quirrel-dev/quirrel/blob/153299597118e8af30277a6c2fae09762a8fa638/src/api/worker/index.ts#L143

but it looks like it's hanging somewhere between

**Comment by rahmonzoda** [comment]
I rolled back to v14.11.0 node version and it looks like start working

version v17.9.0 still not working

**Comment by Skn0tt** [comment]
that's weird. I don't have an idea what's causing this. if you find out, let me know and I'll fix.
