### ISSUE TITLE
QUIRREL_BASE_URL environment variable not working in development

### ISSUE THREAD

**Issue by rmiller61** [quirrel-dev/quirrel#1028]
## Bug Report

**Current Behavior**
I'm using local-ssl-proxy for development which means my base url is https://localhost:3000. But no matter what I set QUIRREL_BASE_URL to in my .env files, Quirrel seems to still use the default (insecure) http://localhost:3000 as the base url. As a result, my queues/events are not working.

**Input Code**

.env
```ts
QUIRREL_BASE_URL="https://localhost:3000"
```

package.json
```ts
  "scripts": {
    "dev": "concurrently 'blitz dev -p 3001 & local-ssl-proxy --key localhost-key.pem --cert localhost.pem --source 3000 --target 3001' 'quirrel'",
    ...
  },
```

**Expected behavior/code**
Quirrel should be using the environment variable I've set for the base url.

**Environment**

- Quirrel 1.9.3
- Node 16.13.2
- Yarn 1.22.18
- Blitz 0.45.4

**Possible Solution**

**Additional context/Screenshots**
In the development UI, on the network tab it is showing the wrong (default) base URL being called.
<img width="1500" alt="Screen Shot 2022-08-17 at 9 31 03 PM" src="https://user-images.githubusercontent.com/13571347/185275905-76ef0a86-18cd-4a1e-a2e4-fbc8d2d99036.png">

**Comment by Skn0tt** [comment]
Judging from the code you sent, it looks like you should be using `https://localhost:3001`. Does that work?

**Comment by rmiller61** [comment]
Nope I've tried every variation of https:// vs http://, port 3000 vs 3001. The problem seems to be that Quirrel is ignoring my `QUIRREL_BASE_URL` environment variable. At least that's what my assumption would be from that screenshot of the network tab where the url param is always http://localhost:3000 regardless of what the environment variable is.

**Comment by Skn0tt** [comment]
The QUIRREL_BASE_URL variable is picked up by the Quirrel npm library you're importing in your Blitz app. Can you check if other environment variables from that file are being picked up by Blitz?

**Comment by Skn0tt** [comment]
Aside from that, could you elaborate on why you're trying to guard Quirrel behind an SSL proxy locally?

**Comment by Skn0tt** [comment]
When you write "the application seems to still use the default" in the issue, what is "the application" referring to, Quirrel or your Blitz application?

**Comment by Skn0tt** [comment]
If it's referring to Quirrel, I think I have an idea of what's causing what you're seeing, and it checks out that you're seeing the Dev UI call the local quirrel server via HTTP and not HTTPS. In local dev, I consider that very acceptable. Can you elaborate on why that's a problem for your usecase?

**Comment by Skn0tt** [comment]
I think the problem is that in your `dev` script, the `'quirrel'` call won't pick up `.env` files. Could you try changing it to `'QUIRREL_BASE_URL="http://localhost:3001" quirrel'`? That should make it pick up the environment variable. Alternative, you can look at tools like https://www.npmjs.com/package/dotenv-cli.

**Comment by rmiller61** [comment]
perfect, that worked. Much thanks! I'll mark this as closed.
