### ISSUE TITLE
CronJob duplicates on Vercel

### ISSUE THREAD

**Issue by markkkkas** [quirrel-dev/quirrel#1029]
## Bug Report

**Current Behavior**
Currently I have one `CronJob` which works fine, but when i redeploy my "production" environment in Vercel, using [documentation provided method](https://docs.quirrel.dev/deploying/) I see duplicated `CronJob` in my ui.quirrel.dev webpage.
Is this behaviour expected, or "old" `CronJob` instances should be cleaned up after new deployment?

**Input Code**
Just regular `CronJob`
```ts
import { CronJob } from "quirrel/next";

export default CronJob(
  "api/customCron",
  async () => {
    // await ...
  }
)
```

**Expected behavior/code**
I expect that old `CronJob` instances should be deleted and only one is visible in ui.quirrel.dev webpage.

**Environment**

- Quirrel version: 1.9.2
- Node/npm version: node 16/pnpm 7.9.5
- Nextjs 12.2
- Vercel

**Additional context/Screenshots**
package.json
```json
{
  "scripts": {
    "build:vercel": "next build && quirrel ci"
  }
}
```

![CleanShot 2022-09-01 at 22 24 49](https://user-images.githubusercontent.com/48568793/187995978-b0e7ee32-4b5c-4ddd-82c3-0ef06b4fbaf8.png)

Thank you in advance!

**Comment by Skn0tt** [comment]
`quirrel ci` is supposed to clean up old cronjobs, that's right. Here's the code: https://github.com/quirrel-dev/quirrel/blob/2feba926bc3836a4f0cb40f63b3ffe65aa9ee2eb/src/api/scheduler/jobs-repo.ts#L301-L356

Not sure what's causing this. Could you try to write up some a minimal reproduction steps that I can use to reproduce this issue? That'd help me resolve it.

**Comment by Skn0tt** [comment]
Closing this, feel free to reopen.

**Comment by markkkkas** [comment]
Hey @Skn0tt, sorry for late reply I cannot reopen, so im writing it here.

Im currently using this setup:
1. Vercel for next.js app
2. Self-hosted quirrel on netlify

Build command: `"build:vercel": "next build && quirrel ci"`

As you can see, quirrel tried to update cron jobs
![image](https://user-images.githubusercontent.com/48568793/204782809-483aa270-14af-4d32-96b9-9b6a75056f64.png)

And unfrotunately UI shows 2 jobs, which are actually executed 2 times, so if i rerun this, it will be 3 jobs, 4 jobs and etc...
![image](https://user-images.githubusercontent.com/48568793/204783012-6571f950-8846-4bce-9147-65ffdadf6287.png)
![image](https://user-images.githubusercontent.com/48568793/204783049-decbd79c-e404-456e-8b0c-950b2a7cc7f6.png)

**Comment by Skn0tt** [comment]
> Self-hosted quirrel on netlify
Could you elaborate on how you set that up? I'm not aware of any way of hosting the Quirrel app on Netlify, so it'd be very interesting to learn what you mean by this.

> And unfrotunately UI shows 2 jobs,

I have the suspicion that these two jobs, which are seemingly to the same URL, share the same path but have different hosts. The UI only shows the path, but if you hover over it, [the tooltip should show the full URL](https://github.com/quirrel-dev/quirrel/blob/2af94f249fd8e18a7cfc486148289d61d8cafd35/development-ui/src/pages/cron.tsx#LL17). My suspicion is that one is `https://preview-a.vercel.app/api/populate-patients/cron` and the other is `https://preview-b.vercel.app/api/populate-patients/cron`, or something similar. That breaks Quirrel's cron deduplication.
If that's the case, check if the `QUIRREL_BASE_URL` variable is the same for all your deployments. `quirrel ci` relies on that to properly deduplicate.

**Comment by markkkkas** [comment]
@Skn0tt 
Sorry for confusing you, it's not Netlify, its fly.io. I followed this approach https://dev.to/remixtape/self-hosting-quirrel-5af7

Regarding the `QUIRREL_BASE_URL` looks like im missing it! Ill try to add it and then will try to redeploy.

**Comment by markkkkas** [comment]
@Skn0tt looks like that we managed to fix it! Thank you very much for support.
