### ISSUE TITLE
Unable to connect to UI or CI tasks. Always becoming Unauthenticated

### ISSUE THREAD

**Issue by octalpixel** [quirrel-dev/quirrel#1037]
## Bug Report

**Current Behavior**
I have hosted Quirrel using the Railway template and cannot authenticate to the server to push the task or even view the UI. I had previously used the template and worked fine, I am creating a new instance for a different project and it is not working. I double-checked the keys yet always return as an error.

In the UI  : "Please authenticate with your QUIRREL_TOKEN via the top-left connection menu."
In the console: ``` Updating server ...
Something went wrong: Unauthenticated```

**Environment**

- Quirrel version: v1.9.3 (I believe this is the latest docker image version)

**Comment by octalpixel** [comment]
@Skn0tt  followed this https://docs.quirrel.dev/deploying and  https://dev.to/remixtape/self-hosting-quirrel-5af7

**Comment by Skn0tt** [comment]
That looks like the token you're using is invalid. Are you sure you've correctly set the token you [aquired](https://docs.quirrel.dev/deploying/#acquire-a-token)? Another source of error I could think about is that your redis instance is not configured to persist data, so all token information is lost on the Quirrel side after a while.

**Comment by Skn0tt** [comment]
That's all the pointers I can think of right now. If that doesn't help, please provide me a detailed step-by-step guide for how to reproduce this setup, so I can test it myself.

**Comment by octalpixel** [comment]
> That's all the pointers I can think of right now. If that doesn't help, please provide me a detailed step-by-step guide for how to reproduce this setup, so I can test it myself.

Thanks for your input @Skn0tt . I dropped you a Twitter message with the relevant link to the hosted version on railway.

**Comment by octalpixel** [comment]
Thanks for helping out @Skn0tt . Devs please see that you copy the token properly, sometimes git bash might break lines unindently :')
