### ISSUE TITLE
CronJobs detection fail silently in 1.12.0

### ISSUE THREAD

**Issue by mr47** [quirrel-dev/quirrel#1089]
## Bug Report

**Current Behavior**
On the latest version cronjobs appear to not work.

**Input Code**

- REPL or Repo link if applicable:

```ts
export default CronJob(
    "api/test",
    "*/1 * * * *",
    async () => {
       console.log("Test");
    }
);
```

**Expected behavior/code**
In UI and in the logs cron jobs are visible.

**Environment**

- Quirrel version: v1.12.0
- Node/npm version: node 18
- Next 13

**Possible Solution**

**Comment by Skn0tt** [comment]
hmm, I wonder if this is related to https://github.com/quirrel-dev/quirrel/pull/1058 🤔

**Comment by Skn0tt** [comment]
I'm having trouble reproducing this locally. @mr47 could you give step-by-step directions on how I can reproduce this - or even better, a reproduction repository? That'd make it a lot easier for me to fix this.

**Comment by mr47** [comment]
@Skn0tt Hey sure, I'll share repo and all details that I have. 

Some Info: 

Next 13,
Quirrel 1.12.0
<img width="1011" alt="Screenshot 2022-11-04 at 22 13 31" src="https://user-images.githubusercontent.com/651943/200066194-22555fe6-fac3-4d05-a4b7-1d0afef37a19.png">


<img width="1541" alt="Screenshot 2022-11-04 at 22 14 53" src="https://user-images.githubusercontent.com/651943/200066305-fd541e66-da66-4fea-91f9-6f4ef576d2c9.png">


```json
{
  "name": "quirrel-bug",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "concurrently 'next dev' 'quirrel'",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next/font": "^13.0.2",
    "concurrently": "^7.5.0",
    "next": "13.0.2",
    "quirrel": "^1.12.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "eslint": "8.26.0",
    "eslint-config-next": "13.0.2"
  }
}

```

**Comment by mr47** [comment]
@Skn0tt bare bone repo that shows no cronjobs https://github.com/mr47/quirrel-bug

<img width="1541" alt="Screenshot 2022-11-04 at 22 20 58" src="https://user-images.githubusercontent.com/651943/200067374-929579e6-fcfa-47d2-adfe-de208cf72638.png">

**Comment by Skn0tt** [comment]
that's super helpful, thanks. looks like that's a regression that was introduced by a breaking change in commander.js (see https://github.com/quirrel-dev/quirrel/pull/999). Working on a fix.

**Comment by Skn0tt** [comment]
@all-contributors please add @mr47 for bug
