### ISSUE TITLE
sveltekit codespaces cron job not working

### ISSUE THREAD

**Issue by JonathonRP** [quirrel-dev/quirrel#1121]
## Bug Report

**Current Behavior**
similar to #1089
I have a running in codespaces with a single cron job in sveltekit that shows in status but doesn't show in cron tab
and is not running.

**Input Code**

- REPL or Repo link if applicable:
https://github.com/JonathonRP/PersonalFinanceDashboard/tree/dev

**Expected behavior/code**
cron should be picked up, running and visible in cron tab

**Environment**

- Quirrel version: [e.g. v1.13.1]
- Node/npm version: [e.g. Node 14/npm 6]
- codespaces
- sveltekit

**Comment by Skn0tt** [comment]
Hi @JonathonRP, thanks for the report! There was a bug where the `--host` arg wasn't respected everywhere in the codebase. https://github.com/quirrel-dev/quirrel/pull/1122 fixes that, i'll let you know once it's released.

@all-contributors please add @JonathonRP for bug

**Comment by Skn0tt** [comment]
https://github.com/quirrel-dev/quirrel/releases/tag/v1.13.2 contains the PR, please let me know if that fixes it for you.

**Comment by JonathonRP** [comment]
this did not solve my issue, if it helps here are the errors I get in UI dev console.
![image](https://user-images.githubusercontent.com/30267655/219378553-a35edbc2-bc4c-4304-89ba-bca1c96fcaeb.png)

**Comment by JonathonRP** [comment]
Thank you @Skn0tt, I tried a few work ways to tell Quirrel port 5000 but never changed the results. also, note that working in my local environment now with no changes, Quirrel works and picks up CronJob.

**Comment by Skn0tt** [comment]
Okay, so did this fix your problem, or should I look into it again?

**Comment by JonathonRP** [comment]
@Skn0tt please look into it again.

**Comment by Skn0tt** [comment]
When running `QUIRREL_BASE_URL=http://0.0.0.0:5000 npx quirrel` in a codespace with your repo, things are running fine. I noticed it doesn't work with `.env`, could it be that you've tried that instead? The quirrel CI doesn't pick up your `.env` automatically, you can take a look at https://www.npmjs.com/package/dotenv-cli if you're looking for that.

**Comment by JonathonRP** [comment]
I will give this a try, and it is good enough for me to close this issue now.
