### ISSUE TITLE
Node v19 Support

### ISSUE THREAD

**Issue by etcimon** [quirrel-dev/quirrel#1129]
Hello,

Can we have support for Node v19?

```error quirrel@1.13.2: The engine "node" is incompatible with this module. Expected version "14 || 15 || 16 || 17 || 18". Got "19.2.0"```

Thanks

**Comment by Skn0tt** [comment]
Sure! Opened a PR that adds test coverage for it, will ping you when it's shipped.

**Comment by Skn0tt** [comment]
shipped in https://github.com/quirrel-dev/quirrel/releases/tag/v1.13.4!
