### ISSUE TITLE
Bring Native support for Next.js App Directory

### ISSUE THREAD

**Issue by Skn0tt** [quirrel-dev/quirrel#1138]
In https://github.com/quirrel-dev/quirrel/discussions/1136, users asked for how they can use the Next.js App Directory with Quirrel. We should build a ready-made integration.

**Comment by KevinEdry** [comment]
Waiting for this to happen, I cannot integrate Quirrel to my nextjs 13 codebase.
would also love to see a workaround until this will be resolved.

**Comment by gyto23** [comment]
@Skn0tt @KevinEdry

I dont think the queue is even working. I have already tried to run the new next-app. the cron jobs are invoking and they can return some console logs on server, however queue doesnt, nor setting queue for 3 seconds to invoke or manual invoke

<img width="603" alt="image" src="https://github.com/quirrel-dev/quirrel/assets/54277098/9be24ddc-80c6-438c-b94c-404ef4486ff3">

```js
export const docQueue = Queue(
  "/api/queue/doc",
  async (content_id: string) => {
    console.log("payload", content_id);
    const document = await getDocument(content_id);
    const modifiedAt = await getModifiedTime(content_id);

    const article = await prisma.article.update({
      data: {
        content: document,
        content_at: modifiedAt,
      },
      where: {
        content_id,
      }
    });

    revalidatePath(`/article/${article.id}`);
  }
)
export const POST = docQueue;

```

and I called it with (obvious)
```js
 await docQueue.enqueue(
    id,
    {
      // runAt: today.add(3, "second").toDate(),
      runAt: today.add(10 + index, "minute").toDate(),
      id,
    },
```

**Comment by gyto23** [comment]
> @Skn0tt @KevinEdry
> 
> I dont think the queue is even working. I have already tried to run the new next-app. the cron jobs are invoking and they can return some console logs on server, however queue doesnt, nor setting queue for 3 seconds to invoke or manual invoke
> 
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/54277098/247767684-9be24ddc-80c6-438c-b94c-404ef4486ff3.png">
> ```js
> export const docQueue = Queue(
>   "/api/queue/doc",
>   async (content_id: string) => {
>     console.log("payload", content_id);
>     const document = await getDocument(content_id);
>     const modifiedAt = await getModifiedTime(content_id);
> 
>     const article = await prisma.article.update({
>       data: {
>         content: document,
>         content_at: modifiedAt,
>       },
>       where: {
>         content_id,
>       }
>     });
> 
>     revalidatePath(`/article/${article.id}`);
>   }
> )
> export const POST = docQueue;
> ```
> 
> and I called it with (obvious)
> 
> ```js
>  await docQueue.enqueue(
>     id,
>     {
>       // runAt: today.add(3, "second").toDate(),
>       runAt: today.add(10 + index, "minute").toDate(),
>       id,
>     },
> ```

My mistake, Incorrect Base url in env was setup
