### ISSUE TITLE
Cannot install Quirrel using node v.20

### ISSUE THREAD

**Issue by gdrose** [quirrel-dev/quirrel#1149]
## Bug Report

**Current Behavior**
I cannot install Quirrel using node v.20

**Input Code**

```
◀️ npm install quirrel
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: quirrel@1.14.0
npm ERR! notsup Not compatible with your version of node/npm: quirrel@1.14.0
npm ERR! notsup Required: {"node":"14 || 15 || 16 || 17 || 18 || 19"}
npm ERR! notsup Actual:   {"npm":"9.6.6","node":"v20.1.0"}
```

**Expected behavior/code**
installing quirrel (?)

**Environment**

- Quirrel version: 
- Node/npm version: {"npm":"9.6.6","node":"v20.1.0"}

**Possible Solution**

Unfortunately I cannot downgrade my version of node because I have other internal packages that have to run in the v.20

Does anyone have any workarounds in mind I could use? Thanks

**Comment by Skn0tt** [comment]
Node v20 support shipped in https://github.com/quirrel-dev/quirrel/releases/tag/v1.14.1
