### ISSUE TITLE
Add support for CRON jobs

### ISSUE THREAD

**Issue by Skn0tt** [quirrel-dev/quirrel#13]

**Comment by shc023** [comment]
Hello, this SaaS is exactly what we were looking for!

We're looking to run a polling job against an API indefinitely, so support for CRON would be super awesome.

In the meantime though, I'm wondering if it would an easy workaround to make `repeat.times` an optional param, and if `repeat.times` isn't present, then `isFinished` will just never be true? So this way we could have an `/api/startPolling` that'll just schedule the indefinitely repeating job once, basically a working workaround for CRON.

What do you think?

**Comment by Skn0tt** [comment]
That'a a good idea! I'll start working on this tomorrow.
