### ISSUE TITLE
Using a date type in the payload of a queue results in a string type

### ISSUE THREAD

**Issue by scisteffan** [quirrel-dev/quirrel#163]
## Bug Report

**Current Behavior**
When I set the input parameter of the Queue function to a date type and pass in a date to the enqueue function, the type of the parameter is a string.

**Input Code**

- REPL or Repo link if applicable:

```ts
export default Queue(
  "api/generateRosterQueue", // the path of this API route
  async (date: Date) => {
    console.log(`Generate roster task executing for date: ${typeof date}`)
  }
)

await GenerateRosterQueue.enqueue(new Date())
```

**Expected behavior/code**
I expect the `tyoeof date` to return a Date type, but it returns a string

**Environment**

- Quirrel version: 1.2.0
- Node/npm version: 15.8.0 / 7.5.1

**Additional context/Screenshots**

<img width="486" alt="Screenshot 2021-03-05 at 16 01 48" src="https://user-images.githubusercontent.com/2676185/110140534-1986d800-7dcc-11eb-923d-eeb53530c982.png">

**Comment by Skn0tt** [comment]
Hi @scisteffan, thanks for opening this issue! Definitely a good idea. I'll put up a PR to integrate [SuperJSON](https://github.com/blitz-js/superjson), that should solve it :)
