### ISSUE TITLE
[v1.4.3] Type error: Cannot find name 'window'

### ISSUE THREAD

**Issue by matthieuh** [quirrel-dev/quirrel#256]
## Bug Report

**Current Behavior**
Updating to version 1.4.3 I'm getting the error `Type error: Cannot find name 'window'` building my project. Could be related to this issue https://github.com/lquixada/cross-fetch/issues/104 unfortunately I can't found a workaround to make it works (like adding a resolution to the latest cross-fetch version).

Disabling all imports from Quirrel on my project import quirrel `import { Queue } from "quirrel/blitz"` it's building fine.

**Environment**

- Quirrel version: v1.4.3
- Node/npm version: Node v15.13.0

**Comment by Skn0tt** [comment]
Could you try if `1.4.3-fix-256` fixes the issue? (`npm i quirrel@1.4.3-fix-256` / `npm i quirrel@danger`)

**Comment by matthieuh** [comment]
Perfect it's fixing the issue 👌

**Comment by Skn0tt** [comment]
Published in [v1.4.4](https://github.com/quirrel-dev/quirrel/releases/tag/v1.4.4)
