### ISSUE TITLE
Custom cron timezone

### ISSUE THREAD

**Issue by Skn0tt** [quirrel-dev/quirrel#304]
## Feature Request

For better readability, there should be a way to specify the timezone in which a cron job is interpreted.

```ts
// just an example
export default Cron("...", "* * * * 1", "Europe/Berlin", async () => ...)
```

**Comment by rfoel** [comment]
Isn't it a UI problem? The queue and cron jobs can be scheduled to UTC and while visualizing them on the page it can be an option to select a timezone.

I think it's not necessarily good to have timezones on the db.

**Comment by rain2o** [comment]
Hey @Skn0tt , quick question regarding this issue. Until this feature is implemented, what timezone are cron jobs currently executed in? And for event reminders, when sending the `runAt` value, which timezone should we expected it to be in?

I'm guessing UTC, but I didn't see anywhere in the docs that indicated this information and wanted to confirm.

**Comment by Skn0tt** [comment]
hi @rain2o! Correct, [cron jobs are currently scheduled based on UTC](https://docs.quirrel.dev/api/queue#cron-schedule). `runAt` takes a `Date` object, and will schedule for whatever point-in-time is stored in it. It doesn't have a concept of timezone, so to speak.
