### ISSUE TITLE
QUIRREL_BASE_URL should not be necessary at build time

### ISSUE THREAD

**Issue by kivi** [quirrel-dev/quirrel#355]
## Feature Request

When Quirrel is integrated with Blitz or maybe this counts for Next.js as, then it will require to have the ENV `QUIRREL_BASE_URL` set, but at build time, that URL might not be known and can change later.

QUIRREL_BASE_URL could be removed for build time, so no jobs can be executed at build time.

**Comment by Skn0tt** [comment]
Hi @kivi! `QUIRREL_BASE_URL` is indeed required during build time, if you're using `quirrel ci`.
The idea behind requiring it on build time is to communicate that this environment variable should *never* change during the lifetime of a deployment. If that'd happen, you suddenly interact with totally different queues, and that'd be hard to debug!

What's your use-case for making `QUIRREL_BASE_URL` non-required during build? Could you solve it by passing in a dummy value?

**Comment by kivi** [comment]
I don't see the reason to have QUIRREL_BASE_URL during deployment. In my case there is no Quirrel queue needed during build and deployment. I need the at run time time of the app.
Besides, I think it should be possible to change the QUIRREL_BASE_URL. A stateless service, could restart with changed ENV vars. However that is probably not common use case for smaller projects.

In other words. I should be able to build an compile Blitz and Quirrel without QUIRREL_BASE_URL. But it needs to be set, when I start the service.
If I restart I might use the same build, but different ENV's.
Think of it as a container image with a ready build and compiled services. I start that service, with necessary ENV's and expose it's PORT. I could do that again with same image, but the second time I have a different Endpoint and use different ENV's

**Comment by Skn0tt** [comment]
I outlined the reason above: It's about communicating that this environment variable is *absolutely* needed. No application should build without that environment variable. There is indeed no technical necessity, but I prefer having people learn about this during build rather than having their apps break in runtime. And it is indeed only that: A check for existence. It is not inlined into the build, and you're free to change `QUIRREL_BASE_URL` down the line.

I will think about lifting that requirement, though.

**Comment by kivi** [comment]
I see your point. I could live with that. Thanks, you can close this one if you'd like.

Maybe it is just my opinion not to set an ENV that is not used during build.
Now I have to set an ENV during build that is not used at all, so I have to set it to some fake value. As mentioned, I don't have the value at build time. (could lead to misunderstandings, if not documented well. Talking here as a consumer of Quirrel) 
Another case I can think of, you would have to set the ENV even though you never use Quirrel, but just appears to be it in your dependencies. Although that is indeed a weird setup.

Just wondering, if renaming could clarify what `QUIRREL_BASE_URL` and `QUIRREL_URL` are. They could named like: _INVOKER_URL or _EXECUTER_URL

**Comment by Skn0tt** [comment]
The environment variables were named so you don't need to actually know how Quirrel works internally, it should *just work*. `QUIRREL_BASE_URL` is meant to be the *base url* of your application, the `QUIRREL_` prefix is to prevent name clashes. I agree that `QUIRREL_URL` is a bit of a misnomer, `QUIRREL_API_URL` would be a much better fit. I'll update that!

**Comment by Skn0tt** [comment]
Also, I'll keep the `QUIRREL_BASE_URL` build requirement for the time being. It's a safety net that's helpful for most cases. People that wonder about why that's necessary will hopefully find this issue and know that they can put some dummy value :D

(To the future: If you, future reader, came here as expected, please leave a comment so I can estimate how often people actually do that)
