### ISSUE TITLE
Tokens are lost, when running Quirrel and Redis in Kubernetes

### ISSUE THREAD

**Issue by kivi** [quirrel-dev/quirrel#356]
## Bug Report

**Current Behavior**
I am running Redis and Quirrel in Kubernetes cluster. At the moment there are just two pods. After a while the token get's invalid. This might be the case, when Quirrel or Redis is restarted in the Kubernetes node.

**Expected behavior/code**
Generated Tokens should be persistent and saved in a stateful environment.

**Environment**
Kubernetes, Pods

- Quirrel version: ghcr.io/quirrel-dev/quirrel:sha-e27789b

**Possible Solution**

Maybe a persistent volume for Redis? So even if Redis, if Redis holds the Tokens, should re-read the data from persistent storage.

**Comment by Skn0tt** [comment]
Hi @kivi! Quirrel requires the Redis deployment to be persistent, yes. [Added that to the docs](https://github.com/quirrel-dev/quirrel/commit/1f81190665712d442579c85d89c2218b70b54830) for clarification.
