### ISSUE TITLE
CORS on ui.quirrel.dev

### ISSUE THREAD

**Issue by rfoel** [quirrel-dev/quirrel#357]
## Bug Report

**Current Behavior**

While navigating on `ui.quirrel.dev` I keep getting CORS errors while trying to connect on `api.quirrel.dev`.

```
Access to fetch at 'https://api.quirrel.dev/health' from origin 'https://ui.quirrel.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by Skn0tt** [comment]
That's interesting / weird! Which browser are you using?

**Comment by rfoel** [comment]
I'm using Chrome 90.0.4430.93 on macOS 11.3.1.

**Comment by rfoel** [comment]
Also, sometimes it takes a while to connect 
![image](https://user-images.githubusercontent.com/19496473/117543095-bf83d800-aff1-11eb-9a17-2eed329b5a9e.png)

**Comment by Skn0tt** [comment]
If I run `curl -v https://api.quirrel.dev/queues`, I see that it returns `Access-Control-Allow-Origin: *`. This works the same across Safari, Firefox and Chrome.

There have been two recent PRs that could've messed with this #362, #336. Does the issue still exist for you? Maybe one of them has broken / fixed it.

**Comment by rfoel** [comment]
The socket keeps on closing on me now, the CORS problem seem to be gone.

**Comment by Skn0tt** [comment]
I assume you provided a token, right?

**Comment by rfoel** [comment]
Yes, I bookmarked the url provided from the UI

**Comment by Skn0tt** [comment]
Closing automatically, please re-open if the issue still exists.
