### ISSUE TITLE
Swagger docs are down

### ISSUE THREAD

**Issue by rfoel** [quirrel-dev/quirrel#358]
## Bug Report

**Current Behavior**
I tried to access the docs on Swagger but it's currently down: https://api.quirrel.dev/documentation

Also, what bearer token should I use to be able to make requests on Postman for example?

**Comment by Skn0tt** [comment]
If you're running quirrel.dev, use the same token that's in your `QUIRREL_TOKEN` env var.

**Comment by Skn0tt** [comment]
According to https://status.quirrel.dev, there was a brief downtime at that time. So I guess that's why it was down.

**Comment by Skn0tt** [comment]
Hope that solve it! Feel free to reopen if not.
