### ISSUE TITLE
404 error trying to create a job with an endpoint longer than 86 characters

### ISSUE THREAD

**Issue by zyulyaev** [quirrel-dev/quirrel#514]
## Bug Report

**Current Behavior**
Quirrel API returns 404 error when trying to create or query a queue with endpoint URL longer than 86 characters long.

**Input Code**

```ts
// QUIRREL_BASE_URL=https://some-very-long-subdomain.example.org
const PATH = 'very/long/queue/endpoint/url/with/a/lot/of/characters'
const queue = Queue(PATH, () => {})
queue.enqueue(...)
```

**Expected behavior/code**
I expect the job to be created.

**Environment**

- Quirrel version: [e.g. v1.5.0]
- Node/npm version: [e.g. Node 12/npm 7]

**Additional context/Screenshots**
I think this should be a pretty common case when working with Vercel preview environments. Our preview environments' domain names are 50 just by themselves.

This is what you get when trying to create a job with a long endpoint URL:
<img width="1422" alt="Screenshot 2021-06-25 at 18 52 47" src="https://user-images.githubusercontent.com/9340671/123451914-9988b600-d5e6-11eb-9634-614df80dbbaf.png">

And this is what you get with URL not that long:
<img width="1416" alt="Screenshot 2021-06-25 at 18 56 31" src="https://user-images.githubusercontent.com/9340671/123452533-2cc1eb80-d5e7-11eb-9124-5f33e4aadee5.png">

**Comment by Skn0tt** [comment]
whew, that's an interesting observation. I'll take a look on monday!
