### ISSUE TITLE
CronJob in vercel does not work

### ISSUE THREAD

**Issue by saiichihashimoto** [quirrel-dev/quirrel#544]
None of the CronJobs are calling our endpoints when I deploy them on vercel and have `vercel ci` inside of my `vercel-build` script, and I can confirm it's actually building in the build log.

![image](https://user-images.githubusercontent.com/2819256/124179241-282e8480-da78-11eb-8674-98385935b399.png)

In the quirrel dashboard, the API Calls _are_ going up, so it looks like it's actually doing something:

![image](https://user-images.githubusercontent.com/2819256/124179424-76dc1e80-da78-11eb-826f-a9eccb80b8ad.png)

However, in vercel, I'm not seeing any logs in my log drain of the endpoint being called whatsoever. When I go to it in the browser (which obviously won't work) it DOES generate a log of visiting the endpoint, so I know if quirrel was actually reaching it then I would see something.

```ts
// src/pages/api/v1/crons/orders/cleanup/index.ts
import { CronJob } from 'quirrel/next';

const cron = CronJob('api/v1/crons/orders/cleanup', '0 * * * *', async (...args: any[]) => {
	...
});

export default cron;
```

It's not the file pathing. I have a `Queue` also running using the same file structure and path so, as long as it's consistent between them, then it should be fine.

How do I make this work?

**Comment by saiichihashimoto** [comment]
How is this meant to be working @Skn0tt? It looks like, whether its a dry run or not, `quirrel ci` ends up [only logging to the console](https://github.com/quirrel-dev/quirrel/blob/main/src/cli/commands/update-cron.ts#L121). Not sure how that results in a cron actually getting scheduled.

**Comment by Skn0tt** [comment]
Hi @saiichihashimoto! Your code seems fine, I don't immediately see why it doesn't work. I expect you're on the most current version of Quirrel?

**Comment by saiichihashimoto** [comment]
That is correct.

**Comment by saiichihashimoto** [comment]
@Skn0tt Is there somewhere I can verify the crons are actually getting registered? The build log show that these jobs "will" be created, I'd like to see that it's actually created so I can debug this properly.

**Comment by Skn0tt** [comment]
I checked my logs, and it indeed looks like none of these jobs were created. I can only see a lot of checks if they actually exists, which all return 404s ...

**Comment by Skn0tt** [comment]
The easiest way for you to test this would be to run it locally. Run `quirrel` to start your local dev environment as ususally, then run `quirrel ci` locally. You should then see the cron job appear.

**Comment by Skn0tt** [comment]
You can also connect the Quirrel UI (ui.quirrel.dev) to Production to check if the Cron jobs were created.

**Comment by saiichihashimoto** [comment]
Few things:

- I just changed the path to the cron and deployed. I can see in the code that it's supposed to [log something when it deletes old crons](https://github.com/quirrel-dev/quirrel/blob/c209fec7dcf8aa0a4ff433aca758111fd15ce352/src/cli/commands/update-cron.ts#L82), and since it's not logging anything, that's evidence no jobs are being created.
- I used the Quirrel UI to connect to Production and I see no Cron jobs, so that's more evidence no jobs are being created.

**Comment by saiichihashimoto** [comment]
When using `quirrel` locally, the crons get created with the locally running `quirrel`. It's in my ci process where I run `quirrel ci` that I have issues.

**Comment by saiichihashimoto** [comment]
Can you explain where in `quirrel` the request to make jobs actually occurs? All this does is log: https://github.com/quirrel-dev/quirrel/blob/c209fec7dcf8aa0a4ff433aca758111fd15ce352/src/cli/commands/update-cron.ts#L121

**Comment by Skn0tt** [comment]
Oh, yes ... Apparently https://github.com/quirrel-dev/quirrel/pull/428 broke this. I should add a test for this 😅 Will fix in the coming days.

**Comment by saiichihashimoto** [comment]
Until then, what version should I switch to to make this work for myself in the time being?

**Comment by saiichihashimoto** [comment]
Because when I look at the diff for #428, it looks like it was still [only just logging](https://github.com/quirrel-dev/quirrel/pull/428/files#diff-b4acba333eb9c72daf1f2a07200fe751c5810433c67c24d8f32d7938a9e0e637L128) at the time.

**Comment by saiichihashimoto** [comment]
I have a sense that I must be looking in the wrong place because, as far back as I go, I can't find anywhere that it's doing something different than just logging at that point.

**Comment by saiichihashimoto** [comment]
![image](https://user-images.githubusercontent.com/2819256/124310736-42c53400-db32-11eb-9754-1da4fb537f6f.png)

Not sure if that is the issue. Just deployed a change without the CronJobs and it actually "removed" them. So I'm very uncertain what is happening, especially since the UI doesn't show them either.

**Comment by Skn0tt** [comment]
Before #428, there were some side-effects in `CronDetector` that created the jobs. Going back to v1.5.0 should yield correct behaviour. Sorry for any inconvenience caused, I‘ll publish a fix when I‘m back at my computer.

**Comment by Skn0tt** [comment]
Hi @saiichihashimoto! #550 was published in [v1.6.1](https://github.com/quirrel-dev/quirrel/releases/tag/v1.6.1), please update and check if that fixes the issue for you.

**Comment by maxfi** [comment]
@Skn0tt [v1.6.1](https://github.com/quirrel-dev/quirrel/releases/tag/v1.6.1) fixes this issue for me. Thanks. 🙏

**Comment by saiichihashimoto** [comment]
Now we have the inverse happening @Skn0tt 

![image](https://user-images.githubusercontent.com/2819256/124792190-67465500-df12-11eb-8f1f-f68eb6416ec3.png)

Every deployment, it's telling me they will be removed... every deployment. I did remove the code, but I'm not sure why it's happening every time. I'm also seeing in my logs that the cron is indeed still being run hourly.

**Comment by Skn0tt** [comment]
Thanks for reporting. That seems unrelated, I opened #583 to track it.

**Comment by callum-veloxcommerce** [comment]
I'm also having issues running cron jobs on vercel vs local. Checked using https://ui.quirrel.dev/ and when invoking the job on local it runs perfectly. When invoking the job on production I just get a console log that the job has been received and none of the other console logs or queue jobs it kicks off are logged at all. All working perfectly on local, I'm running quirrel on fly.io if that sheds any light, regular queue jobs work fine on production.

**Comment by Skn0tt** [comment]
Hi Callum! Not sure what's causing this, but happy to help. Could you open a separate issue, and provide a reproduction repo + steps for how I can reproduce this? That way I can take a look to see what's happening.

**Comment by callum-veloxcommerce** [comment]
I'll get around to creating a simplified copy for you to debug tonight, as I'm not using GitHub for it atm. Thanks for the prompt response
