### ISSUE TITLE
Get 404 when trying reach token endpoint to create a new token

### ISSUE THREAD

**Issue by davidsoderberg** [quirrel-dev/quirrel#580]
## Bug Report
**Current Behavior**
I have followed the steps to deploy Quirrel on my own hosting. but when I get to this step:
https://docs.quirrel.dev/deploying#acquire-a-token
I get an 404 when I try to do that request.
I can access ui and login so thats not an problem :)

**Expected behavior/code**
I can do https://docs.quirrel.dev/deploying#acquire-a-token

**Environment**
- Quirrel version: 1.6.1

**Comment by Skn0tt** [comment]
Hi @davidsoderberg! Have you set the `PASSPHRASE` environment variable?

**Comment by Skn0tt** [comment]
Oh shoots, it's actually called `PASSPHRASES`(plural). Does that fix your issue? https://github.com/quirrel-dev/quirrel/blob/54641d15bc224d1819e3d5c54b91024aeea0c680/src/api/main.ts#L11

**Comment by Skn0tt** [comment]
@allcontributors please add @davidsoderberg for docs

**Comment by davidsoderberg** [comment]
No that did not solve my problem :(

**Comment by Skn0tt** [comment]
Tried it locally, works for me. What image are you using precisely? I'm on `ghcr.io/quirrel-dev/quirrel:main`.

**Comment by davidsoderberg** [comment]
I am running the dockerfile in this repos main branch at railway.app.

**Comment by Skn0tt** [comment]
Tried that one too, and it works for me. Could you provide a bash script that I can use to reproduce your exact bug on a fresh machine?

**Comment by Skn0tt** [comment]
Or, before you do that, what's the exact `curl` command you run?

**Comment by davidsoderberg** [comment]
The one specified in documentation.
`curl --user ignored:{PASSPHRASE} -X PUT {QUIRREL_SERVER_URL}/tokens/{NAME_OF_TOKEN}`

**Comment by Skn0tt** [comment]
So e.g. `curl --user ignored:mysupersecurepassphrase -X PUT david-quirrel.railway.app/tokens/test`?

**Comment by davidsoderberg** [comment]
Yes exactly

**Comment by davidsoderberg** [comment]
But with https://

**Comment by Skn0tt** [comment]
If you go to `/documentation`, can you see the `/tokens` endpoint in the OpenAPI Docs?

**Comment by davidsoderberg** [comment]
No

**Comment by Skn0tt** [comment]
That points towards the `PASSPHRASES` environment variable not being set properly. Can you verify it actually gets passed into the container?

**Comment by davidsoderberg** [comment]
Yes that was the problem, but mainly it was because of the doc did not state correct ENV.
