### ISSUE TITLE
Obsolete Jobs not being removed

### ISSUE THREAD

**Issue by Skn0tt** [quirrel-dev/quirrel#583]
(copied from #544:)

Now we have the inverse happening @Skn0tt 

![image](https://user-images.githubusercontent.com/2819256/124792190-67465500-df12-11eb-8f1f-f68eb6416ec3.png)

Every deployment, it's telling me they will be removed... every deployment. I did remove the code, but I'm not sure why it's happening every time. I'm also seeing in my logs that the cron is indeed still being run hourly.

_Originally posted by @saiichihashimoto in https://github.com/quirrel-dev/quirrel/issues/544#issuecomment-875727337_

**Comment by Skn0tt** [comment]
@saiichihashimoto What's your value of `QUIRREL_BASE_URL`? I have a feeling this happens based on wether it ends on `/` or not.

**Comment by saiichihashimoto** [comment]
![image](https://user-images.githubusercontent.com/2819256/124814827-180d1e00-df2c-11eb-8570-b7efe34cd60e.png)

It only happens for me in my preview environments, so that's how the `QUIRREL_BASE_URL` is defined.

**Comment by Skn0tt** [comment]
Is this how it'd go?

1. You open a Preview Environment, the first deploy is made. `quirrel ci` outputs that it created two new jobs, because there's two jobs in your code.
2. You push a commit that removes two of the jobs. `quirrel ci` outputs that it removed the two obsolete jobs.
3. You push another commit that changes nothing about the jobs. `quirrel ci` outputs that it removed the two obsolete jobs (which apparently didn't get deleted the last time).

1. and 2. are fine, but 3. should rather be: "there are no obsolete jobs, so I cant remove anything!"

Please confirm that I understood the setup right.

**Comment by saiichihashimoto** [comment]
That's correct.

**Comment by saiichihashimoto** [comment]
Since the obsolote jobs aren't being removed, they've been using up my queue usage as well. Is there any way to solve this sooner rather than later?

**Comment by Skn0tt** [comment]
I‘ll be tackling this issue next week. I am aware this means additional API calls, but rest assured I‘ll deduct them in case you exceed your quota.

**Comment by Skn0tt** [comment]
This issue seems to be a conceptual one:

Suppose there's two preview deployments A and B, both share the same Quirrel token. Compared to production, A adds a CronJob, B doesn't. Now when A is deployed, it creates the CronJob - when B is deployed, it sees the job, and tries to remove it b/c it doesn't see it locally. b/c it mixes up prefixes, it ends up not being able to remove them.

Instead, B shouldn't try to fumble with CronJobs made by A at all. Will open a PR to implement this.
