### ISSUE TITLE
UI: Headbar isn't responsive

### ISSUE THREAD

**Issue by Skn0tt** [quirrel-dev/quirrel#608]
The Headbar isn't responsive anymore, happened sometime in the last commits.

**Comment by jakobo** [comment]
I can get a fix for this in in about 8-10 hours if you aren't already working on it. In Nav.tsx, there is a missing `hidden` on the horizontal menu, and a missing `hidden md:block` on the horizontal version of the feedback link. With those classes in place, we get the following UI with the working menu:

![image](https://user-images.githubusercontent.com/1795/140471984-3ee03b60-4fe9-468f-8b53-1969e0363596.png)

**Comment by Skn0tt** [comment]
Oh, that would be lovely!

**Comment by jakobo** [comment]
Caught me before I logged off for the night. PR incoming and will check in the AM if there's any requested changes.
