### ISSUE TITLE
Exclusive doesn't seem to work

### ISSUE THREAD

**Issue by mattjis** [quirrel-dev/quirrel#717]
## Bug Report

**Current Behavior**
All queues were triggered by quirrel at the same time, causing certain third-party rate limits to be hit, and all the processes to fail.

	await RaffleQueue.enqueue(null, {
		id: sanityProduct.shopifyId, // IDs were all different
		override: true,
		exclusive: true,
		runAt: new Date(sanityProduct.date) // six of these dates were the same
	})

**Expected behavior/code**
I expected Quirrel to callback one-by-one, waiting for each to finish before calling another.

**Environment**

- Quirrel version: 1.7.0
- Node/npm version: Node 14

**Possible Solution**

**Additional context/Screenshots**
<img width="792" alt="Screen Shot 2021-08-14 at 11 32 28 am" src="https://user-images.githubusercontent.com/21289982/129432865-dd20c574-b245-420f-b50a-7fe293ca5a14.png">

**Comment by Skn0tt** [comment]
Hi @mattjis! I tried reproducing your issue as part of Owl (Quirrel's custom queueing library): https://github.com/quirrel-dev/owl/pull/176 While I found an unrelated bug as part of this, it doesn't seem like I could replicate what you're seeing. Can you confirm this errors because of concurrent calls? "Shopify didn't receive the orders correctly" could point towards something entirely different.

**Comment by mattjis** [comment]
@Skn0tt Thanks for looking in to this!

The "Shopify didn't receive the orders correctly" is an error thrown by my application when it's getting errors back from Shopify. These errors were because the rate limit was being hit. 

I'm going to double check all of my code again and make sure there's nothing that would allow it to ever hit this limit (as long as it's not running concurrently). I'll update this soon.

**Comment by mattjis** [comment]
@Skn0tt I am able to reproduce the issue in my local environment. 

Shall I just paste the 2 test files below?

**Comment by Skn0tt** [comment]
Great, please paste your test files, yes!

**Comment by mattjis** [comment]
`scheduler.js`

	import Queue from "pages/api/quirrel/queue"
	
	function generateRandomID() {
		return String(Math.floor(Math.random() * Date.now()))
	}
	
	async function handler(req, res) {
		const inTenSeconds = new Date()
		inTenSeconds.setSeconds(inTenSeconds.getSeconds() + 10)
	
		await Queue.enqueue(null, {
			id: generateRandomID(),
			override: true,
			exclusive: true,
			runAt: inTenSeconds
		})
	
		await Queue.enqueue(null, {
			id: generateRandomID(),
			override: true,
			exclusive: true,
			runAt: inTenSeconds
		})
	
		await Queue.enqueue(null, {
			id: generateRandomID(),
			override: true,
			exclusive: true,
			runAt: inTenSeconds
		})
	
		await Queue.enqueue(null, {
			id: generateRandomID(),
			override: true,
			exclusive: true,
			runAt: inTenSeconds
		})
	
		await Queue.enqueue(null, {
			id: generateRandomID(),
			override: true,
			exclusive: true,
			runAt: inTenSeconds
		})
	
		return res.json({
			success: true
		})
	}
	
	export default handler

`queue.js`

	import { Queue } from "quirrel/next"
	
	export function sleep(ms, result) {
		return new Promise((res) => setTimeout(res, ms, result))
	}
	
	export default Queue("api/quirrel/queue", async (payload, meta) => {
		console.log("Begin processing, this will take 5 seconds...")
		await sleep(5000)
	
		console.log("Processing complete.")
		return
	})

**Comment by mattjis** [comment]
The console log looks like the following:

	[0] Received job to api/quirrel/queue:  null
	[0] Begin processing, this will take 5 seconds...
	[0] Received job to api/quirrel/queue:  null
	[0] Begin processing, this will take 5 seconds...
	[0] Received job to api/quirrel/queue:  null
	[0] Begin processing, this will take 5 seconds...
	[0] Received job to api/quirrel/queue:  null
	[0] Begin processing, this will take 5 seconds...
	[0] Received job to api/quirrel/queue:  null
	[0] Begin processing, this will take 5 seconds...
	[0] Processing complete.
	[0] Processing complete.
	[0] Processing complete.
	[0] Processing complete.
	[0] Processing complete.
	[2] ✔️ Successfully executed 408339363103.
	[2] ✔️ Successfully executed 285742460860.
	[2] ✔️ Successfully executed 946325141067.
	[2] ✔️ Successfully executed 1259490353695.
	[2] ✔️ Successfully executed 506172965047.

I would expect it to execute one-by-one, instead of all at the same time.

**Comment by Skn0tt** [comment]
That is indeed wrong behaviour. Will take a look in the coming days. Is this urgent for you, or can it wait until next week?

**Comment by mattjis** [comment]
We'd love to get it fixed. I've advised my team that they need to make sure nothing ends at the same time (which would trigger these concurrent executions) so I'm not expecting any new errors while they're obeying this workaround. 

So it's not URGENT urgent. As long as we don't forget, it should be fine.

**Comment by Skn0tt** [comment]
I was able to reproduce the behaviour in #733. Will debug tomorrow.

**Comment by Skn0tt** [comment]
Fixed & released in [v1.7.1](https://github.com/quirrel-dev/quirrel/releases/tag/v1.7.1)!
