### ISSUE TITLE
Disable output for server in development

### ISSUE THREAD

**Issue by kotx** [quirrel-dev/quirrel#765]
It would be great if there was a `-q`, `--quiet` flag to silent the welcome message (below) and/or all output. 
```
Quirrel
=======
Welcome to the Quirrel development server.

Open your browser and go to
    https://ui.quirrel.dev
to get a better overview over pending jobs.

Quirrel collects completely anonymous
telemetry data about general usage,
opt-out by setting the DISABLE_TELEMETRY
environment variable.

Listening on 127.0.0.1:9181.
```

**Comment by Skn0tt** [comment]
Good idea 👍

**Comment by Skn0tt** [comment]
#767 adds a quiet mode, where log statements are one-liners.

To disable output altogether, there's a [Bash trick](https://www.baeldung.com/linux/silencing-bash-output#3-all-output) that should help.

**Comment by kotx** [comment]
Unfortunately I'm on Windows and using PowerShell so I don't have a cross-platform way to do this currently (unless there's some quiet-exec package out there somewhere... maybe [kattu](https://www.npmjs.com/package/kattu)?), but thanks for the quiet mode addition. Closing for now.

**Comment by kotx** [comment]
Actually I'll leave this open until the PR #767 is merged.
