### ISSUE TITLE
Cron job not executing

### ISSUE THREAD

**Issue by fiddep** [quirrel-dev/quirrel#854]
## Bug Report

Hello again!

**Current Behavior**
Having some new strange problems happening that I can't really explain from existing documentation.
The cron jobs have stopped working all together, as can be seen in the dashboard
![image](https://user-images.githubusercontent.com/12913309/139485284-38c20638-be1e-4e34-b370-5b864d1f5e3f.png)

**Input Code**
The job I'm trying to run is really minimal
![image](https://user-images.githubusercontent.com/12913309/139485397-211a8e21-2ffb-42cb-9a97-22a263d736c0.png)

After deploying to vercel everything looks fine
![image](https://user-images.githubusercontent.com/12913309/139485567-366d129a-9ee0-4b71-9774-e3a313376e1c.png)

**Expected behavior/code**
Would expect the job to execute 06:00 Swedish time and the other one at 00:00 Swedish time

**Environment**

- Quirrel version: 1.7.4
- Node/npm version: node 14.XX and yarn 1.XX (Not 100% sure what Vercel uses)

**Comment by Skn0tt** [comment]
Hey @fiddep! I think this could be related to a recently fixed bug. Could you try re-running `quirrel ci`? e.g. by redeploying your latest build on Vercel.

**Comment by Skn0tt** [comment]
(You can see that in the CLI output, it says „these jobs were obsolete and were removed“. There was a bug where every cronjob was deleted immediately after deployment, which has been fixed since then.)

**Comment by fiddep** [comment]
Did a redeploy and it seems to have fixed it, the jobs are executing again on the correct time.
Interpreted the message to mean that the old version of the jobs had been removed, so never paid it much attention.

Thank a lot for the help! Will close this issue
