### ISSUE TITLE
Time difference is huge in Quirrel UI

### ISSUE THREAD

**Issue by deadcoder0904** [quirrel-dev/quirrel#857]
## Bug Report

**Current Behavior**

It shows weird dates on cronjob but executes it at a proper time.

> Sidenote: Would love a feature that shows time a cron starts & ends in CLI as well. I can't use `console.time()` & `console.timeEnd()` without errors.

So the dates are `11:41:45` & rescheduled at `2021-11-01T06:11:54.200Z`

If you see the time difference, it's `11:41:45` & `06:11:54` which is huge & I'm running my cronjob in like every `10sec` with `30sec` delay like:

```ts
await hello.enqueue(name, {
    id: name,
    delay: '30sec',
    repeat: {
      every: '10sec',
      times: 2, // 2 * 10sec = 20sec
    },
  })
```

**Input Code**

- Repo: See this commit → https://github.com/deadcoder0904/quirrel-log/tree/16dbc610f9392af07b68683159d899c4e7d96800

**Expected behavior/code**

It should show time difference like 30 seconds or appropriate. It looks way off. Maybe a timezone issue?

**Environment**

- Quirrel version: v1.7.4
- Node/npm version: Node v16.1.0 & npm v7.21.0

**Possible Solutions**

I think a 30 seconds later or human-readable format is more suitable. Or show it like the first column but include hours, mins, & secs too.

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/16436270/139634545-2a9b94d0-2fba-4224-990f-56255f915777.png)

**Comment by Skn0tt** [comment]
Hi @deadcoder0904! That absolutely looks like a timezone issue, and I'll have a look at it later today. What timezone are you in, btw?

**Comment by deadcoder0904** [comment]
Indian Standard Timezone GMT+5:30

Also, can you take a look at [my other discussions](https://github.com/quirrel-dev/quirrel/discussions?discussions_q=author%3Adeadcoder0904+) which I'm having a hard-time figuring out :)

**Comment by Skn0tt** [comment]
Found the reason: The *time* column [is localised](https://github.com/quirrel-dev/quirrel/blob/main/development-ui/src/pages/activity.tsx#L24), but the right-most column [is not](https://github.com/quirrel-dev/quirrel/blob/main/development-ui/src/pages/activity.tsx#L46). #858  should fix it. Can you try the deploy preview in there?

**Comment by deadcoder0904** [comment]
Oh yes, it works :)

<img width="1437" alt="Screenshot 2021-11-01 at 2 44 06 PM" src="https://user-images.githubusercontent.com/16436270/139649233-0a926231-edee-4f94-952c-ea143f82eb40.png">

Would love a way to add time in console as well. Like absolute time (just like in columns) or relative time (10 seconds later) besides `Created Job` & `Executing Job`:

```ts
[1] 📝Created Job
[1]    queue: /api/queues/hello
[1]       id: Anon
[1]     body: 040e:soE0xf+5QwmxyYEty0lq1w==:cngP24X4:mbzMpdOMV8uGkSxPtIS9Jw==
[1]
[1] 👟Executing job
[1]   queue: /api/queues/hello
[1]      id: Anon
[1]    body: 040e:soE0xf+5QwmxyYEty0lq1w==:cngP24X4:mbzMpdOMV8uGkSxPtIS9Jw==
```
