### ISSUE TITLE
Error: `encryptionSecret` needs to be 32 characters, but was 36 characters.

### ISSUE THREAD

**Issue by jakobo** [quirrel-dev/quirrel#860]
## Bug Report

**Current Behavior**
When testing Quirrel locally, the encryption secret from quirrel.dev contains dashes amd causes an error. Removing the dashes works.

**Input Code**
1. Create Project & environment
2. Note the token beneath text `This is your token. It'll only be displayed in this session, so take note of it:`
3. Set token as local env value `QUIRREL_ENCRYPTION_SECRET`
4. Attempt to dispatch to a queue

```ts
queue.enqueue(...)
```

**Expected behavior/code**
**expected** Proper enqueue of job
**actual** Error: `encryptionSecret` needs to be 32 characters, but was 36 characters.

**Environment**

- Quirrel version: 1.7.4
- Node/npm version: Node @ v14.8.0, ~~npm @ 7.15.1~~, yarn @ 3.0.2

**Possible Solution**
Either the token shouldn't have dashes, or on dispatch the dashes need to be stripped from the token (I'm guessing this is a side effect of node's crypto functions). Honestly, it's probably much cleaner if the UI never presents a dash-separated token in the first place.

**Additional context/Screenshots**
(can't provide since it's got a token)

**Comment by Skn0tt** [comment]
Hi! The token that quirrel.dev gives to you is an access token and should be written into the `QUIRREL_TOKEN` env var. `QUIRREL_ENCRYPTION_SECRET` should 32 characters long, and it should be generated *by you*, as explained here: https://docs.quirrel.dev/deploying

**Comment by jakobo** [comment]
That's on me. I thought the deploying section was for DIY deployments.
