### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by samuelgoff** [quirrel-dev/quirrel#878]
## Bug Report
`MaxListenersExceededWarning` error encountered after running `npx quirrel` for any length of time (e.g. > 24 hours), even without any queues being created nor utilized. This has also occurred on multiple systems, both Intel i9 & M1 Max architectures, etc.

**Current Behavior**
When running Quirrel via npx in local dev environment, I get the following error after leaving Quirrel running for about a day or so:
```
(node:7438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pmessage listeners added to [RedisMock]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Input Code**
`npx quirrel` (no queues have been created nor utilized during this instance)

**Expected behavior/code**
run reliably without generating a `MaxListenersExceededWarning` warning

**Environment**

- Quirrel version: v1.7.4
- Node: v16.13.0
- npm: v8.1.0
- yarn: v1.22.15
- next.js: v12.0.3

**Comment by Skn0tt** [comment]
Hey @samuelgoff! This issue fell between the cracks, sorry. I've encountered that error previously, too. I've found this to only occur in the development version of Quirrel, though, which is not supposed to run for 24hrs at a time. For production deployments, you should either be using the Docker container or at least connect a Redis instance.

Closing for now.
