### ISSUE TITLE
[Feature Request] Path exclusivity?

### ISSUE THREAD

**Issue by mattjis** [quirrel-dev/quirrel#899]
I'd love to be able to make a single path `api/raffle/process` exclusive amongst other queues of itself, but all other queues are unaffected by this exclusivity.

e.g if I schedule a new `ProcessQueue` while one is already running - it must wait. But if I schedule a `FinaliseQueue` while a `ProcessQueue` is running - it'll go through as normal (as this queue does not have to be exclusive)

What are you thoughts?

**Comment by Skn0tt** [comment]
Can you elaborate on what exactly a `ProcessQueue` and a `FinaliseQueue` are in this context? Quirrel's `exclusive` option is queue-level, so if you set `exclusive: true` for `ProcessQueue` and `exclusive: false` for `FinaliseQueue`, it should show the behaviour you're describing.

**Comment by mattjis** [comment]
@Skn0tt Oh for some reason I was under the impression that ALL jobs would be paused when this one has "exclusive".

Perfect!
