### ISSUE TITLE
quirrel ci causes Vercel build to explode 💥 

### ISSUE THREAD

**Issue by samtgarson** [quirrel-dev/quirrel#94]
## Bug Report

**Current Behavior**
Running `quirrel ci` as part of the Vercel build seems to cause chokidar to watch the entire directory and exceed the `system limit for number of file watchers`.

`package.json`:
```json
{
  "verce-build": "quirrel ci"
}
```

[Repo](https://github.com/samtgarson/hooks)

**Expected behavior/code**
The build runs Quirrel CI with no issues.

**Environment**

- Quirrel version: v1.0.4
- Node/npm version: Node 14 / npm 7

**Possible Solution**

Unable to recreate locally. Originally thought it was because `node_modules` wasn't gitignored, but it occurs with it there. Vercel truncates the logs to 2000 lines so I'm not able to see the top of the stack trace (AFAIK?)

Please let me know if there's any more detail I can provide!

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/6242344/107783143-d3e16d00-6d41-11eb-9f9c-3a2728b2a834.png)

**Comment by Skn0tt** [comment]
Hi @samtgarson, sorry for the bad experience. I'll be looking into it ASAP.

As you mentioned, `quirrel ci` parses `.gitignore` to figure out which files aren't needed (this is the respective code: https://github.com/quirrel-dev/quirrel/blob/main/quirrel/src/cli/parse-gitignore.ts). Apparently, that doesn't work on Vercel 🤔
Let's see what's causing this ...

**Comment by Skn0tt** [comment]
Vercel doesn't seem to upload `.gitignore` when invoked from the command line:
<img width="689" alt="Screenshot 2021-02-12 at 16 25 40" src="https://user-images.githubusercontent.com/14912729/107787169-09408780-6d4f-11eb-8083-4a78fb627a60.png">

I'll add `node_modules` to chokidar's ignore list, that should fix it.

**Comment by Skn0tt** [comment]
Published a fix in `1.0.4-fix-94-2`, will be part of `1.1.0`.

**Comment by samtgarson** [comment]
How odd 🤔 Thanks for the quick fix 🙌
