### ISSUE TITLE
Expose `invokeLocally` or `invokeNow` or something to call job directly in line

### ISSUE THREAD

**Issue by anglinb** [quirrel-dev/quirrel#947]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'm trying to test Quirrel jobs with Jest but I'm not able to easily invoke the code. 

**Describe the solution you'd like**
I would like the `Queue` object to expose a method called `invokeLocally` or similar which simply calls the code in the job w/o talking to quirrel.

**Describe alternatives you've considered**
By convention I export a non-default method which contains all the log for the job then simply wrap in it `Queue` to expose it. 
```
export const updateApplicationConfigCache = async (args: UpdateApplicationConfigCache) => {
// Actual logic of the job here.
}

export default Queue(
  "api/updateApplicationConfigCache", // the path of this API route
  async (args: UpdateApplicationConfigCache) => {
    return updateApplicationConfigCache(args)
  }
)
```

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this.
Maybe a code example?

```
import updateApplicationConfigCache from "app/api/updateApplicationConfigCache"

// Currently
updateApplicationConfigCache.enque({})

// In the future
updateApplicationConfigCache.invokeLocally({})

```

**Comment by Skn0tt** [comment]
Hey Brian! Thanks for opening this issue, this is great input!

If I understand correctly, what you're asking for could also be implemented user-land, with a pattern like this:

```ts
export const updateApplicationConfigCache = async (args: UpdateApplicationConfigCache) => {
// Actual logic of the job here.
}

export const updateApplicationConfigCacheQueue = Queue("api/updateApplicationConfigCache", updateApplicationConfigCache)

export default updateApplicationConfigCacheQueue
```

I'd like to understand better the differences & tradeoffs between this user-land solution and the one you're asking for, especially regarding your personal workflow. Can you elaborate on that?

**Comment by anglinb** [comment]
Hey @Skn0tt! Thanks for following up! Correct, I have implemented that user-land pattern. It's just a little clunky to pull out the typing and writing the method twice instead of once. 🤷  Ideally I would only have to reason about that one export for every invocation. A few reasons I think this makes sense:

- Tests are higher fidelity. If I'm calling `Queue.invokeLocally` instead of this default export, I'm testing my job logic *and* ensuring the configuration is correct. It may seem like a subtle change but I think it's the same as mocking an http request vs calling a controller/function directly. I've previously introduced bugs in that small gap between logic and logic attached to the system.
- Some jobs must run inline to avoid race conditions. For the example, a couple endpoints must update the cache before returning to the user. I could call `invoke` but by running them inline instead of via a new http request all the logs are tied to the same request id which makes it much easier to look up logs.

**Comment by Skn0tt** [comment]
I'm worried that introducing a new `invokeLocally` endpoint will have users expect to have access to the same kind of features they get with `invoke` (`repeat`, `override`, `delay` etc.). Most of them are just not possible build locally, so I'm a bit hesitant to introduce that API.

I'm surprised you write "writing the method twice instead of once". The code snippet I posted doesn't require you to type your method twice, the only overhead are the bottom two lines (which could even be made one). Am I missing something?

**Comment by boredland** [comment]
Wouldn't it be an option to just stub out the handler during tests like so?

```typescript
import type { QuirrelJobHandler } from 'quirrel/next';

export const Queue = <Payload>(
  route: string,
  handler: QuirrelJobHandler<Payload>,
) => {
  return {
    enqueue: (payload: Payload) => {
      return handler(payload, {
        exclusive: false,
        retry: [],
        id: 'lala',
        count: 0,
      });
    },
  };
};
```

**Comment by Skn0tt** [comment]
While that's technically possible, I think in most cases it'll be easier to read if the Queue implementation is extracted into it's own method, and testable independently of Quirrel.

**Comment by boredland** [comment]
this is certainly true if you want to test your queue handler - I use things like that when testing things that rely on queue to have run beforehand.
