### ISSUE TITLE
400 | Error: Please specify QUIRREL_BASE_URL..

### ISSUE THREAD

**Issue by jatidevelopments** [quirrel-dev/quirrel#948]
## Bug Report

**Current Behavior**
When deploying to AWS (Fargate) Quirrel doesn't seem to work. It always asks for the QUIRREL_BASE_URL when calling the queue. I tried setting the QUIRREL_BASE_URL with ```https://``` and without. 

**Input Code**

Queue is in path: /api/emailQueue.ts (NextJS):

````
export default Queue("api/emailQueue", async ({ id }, meta) => {
... 
})
````

Calling the queue:

```ts
emailQueue.enqueue(
          {
            id: r.data.id,
          },
          {
            retry: ["10sec", "60sec", "5min", "15min"],
          }
        )
```

**Expected behavior/code**
Pushing to the queue and don't return an error that the QUIRREL_BASE_URL isn't defined. 

**Environment**

- Quirrel version: 1.8.1
- Node/npm version: Node 16

Does anybody know a solution?

**Comment by Skn0tt** [comment]
hey @jatidevelopments! are you using the hosted Quirrel version (https://quirrel.dev), or a self-hosted instance? could you specify what "it always asks for the QUIRREL_BASE_URL" means? is that a log output you're seeing?

**Comment by jatidevelopments** [comment]
Hi @Skn0tt we are using the hosted Quirrel version. We deploy on AWS. I can't see anything in the Logsoutput but it happens when I try to call the `emailQueue.enqueue` function it returns "400 | Error: Please specify QUIRREL_BASE_URL".

**Comment by Skn0tt** [comment]
Hmm :/ That error is thrown by this line: 

https://github.com/quirrel-dev/quirrel/blob/ba995193d3db6f962c1e324f562f0a69db6daf04/src/client/config.ts#L103

It seems to me that somehow your environment variables aren‘t set correctly. Can you verify that QUIRREL_BASE_URL is indeed specified? For example by logging `process.env.QUIRREL_BASE_URL` right before your `.enqueue` call.

**Comment by jatidevelopments** [comment]
Okay, I will test it. Maybe it's because the env is from the Parameter Store at AWS. Do I need to add ```https://``` in front?

**Comment by Skn0tt** [comment]
Shouldn‘t make a difference. If there‘s no protocol given, it automatically uses `https://`:

https://github.com/quirrel-dev/quirrel/blob/ba995193d3db6f962c1e324f562f0a69db6daf04/src/client/config.ts#L106

but specyfing the protocol also works fine.

**Comment by jatidevelopments** [comment]
<img width="974" alt="Screenshot 2022-02-07 at 16 03 17" src="https://user-images.githubusercontent.com/58979465/152816152-33cc2c5a-c806-4b66-87a0-89abb9381d4b.png">

Now I get this error locally after switching the import from ```quirrel/vercel``` to ```quirrel/blitz```

**Comment by Skn0tt** [comment]
I assume that you were able to fix the QUIRREL_BASE_URL issue.

That error looks like you specified QUIRREL_ENCRYPTION_SECRET locally, but had pending jobs that weren‘t encrypted at all. So now it‘s trying to decrypt an unencrypted payload. Could that be the case?

**Comment by jatidevelopments** [comment]
I know the error
We use react-admin for the admin panel
This only works only at client side
So we disabled SSR
Quirrel cant get the QUIRREL_BASE_URL env on client-side
So yeah we need to create an API endpoint and then call the enqueue function in there

So it's solved! But thanks for the support!
